-- AlterTable
ALTER TABLE `tbDeliveries` MODIFY `status` ENUM('REQUESTED', 'AWAITING_PICKUP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'REQUESTED';

-- AlterTable
ALTER TABLE `tbDeliveryLog` MODIFY `status_novo` ENUM('REQUESTED', 'AWAITING_PICKUP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'RETURNED', 'CANCELLED') NOT NULL;
